# Generated by Django 5.0.1 on 2024-02-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('omniauth', 'user from omniauth'), ('regularauth', 'user from regular auth')]},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, choices=[('http://localhost:3000/src/assets/profiles/3.svg', 'http://localhost:3000/src/assets/profiles/3.svg'), ('http://localhost:3000/src/assets/profiles/6.svg', 'http://localhost:3000/src/assets/profiles/6.svg'), ('http://localhost:3000/src/assets/profiles/2.svg', 'http://localhost:3000/src/assets/profiles/2.svg'), ('http://localhost:3000/src/assets/profiles/4.svg', 'http://localhost:3000/src/assets/profiles/4.svg'), ('http://localhost:3000/src/assets/profiles/5.svg', 'http://localhost:3000/src/assets/profiles/5.svg'), ('http://localhost:3000/src/assets/profiles/1.svg', 'http://localhost:3000/src/assets/profiles/1.svg')]),
        ),
        migrations.AddField(
            model_name='user',
            name='omniauth',
            field=models.BooleanField(default=False),
        ),
    ]
