# docker-compose.yml
version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:16.1
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hypertube
      - POSTGRES_USER=hypertuber
      - POSTGRES_PASSWORD=hypersecret
  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=hypertube
      - POSTGRES_USER=hypertuber
      - POSTGRES_PASSWORD=hypersecret
    depends_on:
      - db
    tty: true
  frontend:
    build: ./frontend
    container_name: frontend
    command: yarn dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true
  api-py:
    build: ./api-torrent
    ports:
      - "8009:8009"
volumes:
  data: {}
