# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    command: yarn dev
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    tty: true

volumes:
  data: {}
