# Generated by Django 5.0.1 on 2024-01-16 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_imdb_rating_alter_movie_peer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1888)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(default='', null=True),
        ),
    ]
