# Generated by Django 5.0.1 on 2024-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_imdb_rating_alter_movie_production_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
