# Generated by Django 5.0.1 on 2024-01-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_subtitle_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_subtitles', to='movie.movie'),
        ),
    ]
