# .github/workflows/check_eslint.yml
name: Check eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.5.0

      - name: Install dependencies
        run: |
          cd frontend
          yarn install
          yarn upgrade eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-plugin-react eslint-plugin-react-hooks

      - name: Check eslint
        run: |
          cd frontend

          yarn lint
